// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject3
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// OpenBrowse - Use 'OpenBrowseParams' to pass parameters into this method.
        /// </summary>
        public void OpenBrowse()
        {

            // Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
            BrowserWindow gomicrosoftcomBrowser = BrowserWindow.Launch(new System.Uri(this.OpenBrowseParams.Url));
        }
        
        /// <summary>
        /// OpenApp - Use 'OpenAppParams' to pass parameters into this method.
        /// </summary>
        public void OpenApp()
        {
            #region Variable Declarations
            BrowserWindow uIMSNPolskaOutlookSkypWindow = this.UIMSNPolskaOutlookSkypWindow;
            #endregion

            // Go to web page 'http://localhost:21867/'
            uIMSNPolskaOutlookSkypWindow.NavigateToUrl(new System.Uri(this.OpenAppParams.UIMSNPolskaOutlookSkypWindowUrl));
        }
        
        /// <summary>
        /// OpenPracownicyList
        /// </summary>
        public void OpenPracownicyList()
        {
            #region Variable Declarations
            HtmlHyperlink uIPracownicyHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIHomePageMyASPNETApplDocument.UIPracownicyHyperlink;
            #endregion

            // Click 'Pracownicy' link
            Mouse.Click(uIPracownicyHyperlink, new Point(85, 24));
        }
        
        /// <summary>
        /// AddNewPracownik - Use 'AddNewPracownikParams' to pass parameters into this method.
        /// </summary>
        public void AddNewPracownik()
        {
            #region Variable Declarations
            HtmlHyperlink uICreateNewHyperlink = this.UIIndexMyASPNETApplicaWindow.UIIndexMyASPNETApplicaDocument.UICreateNewHyperlink;
            HtmlComboBox uIStanowiskoIdComboBox = this.UIIndexMyASPNETApplicaWindow.UICreateMyASPNETApplicDocument.UIStanowiskoIdComboBox;
            HtmlEdit uIImieEdit = this.UIIndexMyASPNETApplicaWindow.UICreateMyASPNETApplicDocument.UIImieEdit;
            HtmlEdit uINazwiskoEdit = this.UIIndexMyASPNETApplicaWindow.UICreateMyASPNETApplicDocument.UINazwiskoEdit;
            HtmlEdit uIPeselEdit = this.UIIndexMyASPNETApplicaWindow.UICreateMyASPNETApplicDocument.UIPeselEdit;
            HtmlInputButton uICreateButton = this.UIIndexMyASPNETApplicaWindow.UICreateMyASPNETApplicDocument.UICreateButton;
            #endregion

            // Click 'Create New' link
            Mouse.Click(uICreateNewHyperlink, new Point(64, 13));

            // Select 'Szef' in 'StanowiskoId' combo box
            uIStanowiskoIdComboBox.SelectedItem = this.AddNewPracownikParams.UIStanowiskoIdComboBoxSelectedItem;

            // Type 'Test' in 'Imie' text box
            uIImieEdit.Text = this.AddNewPracownikParams.UIImieEditText;

            // Type '{Tab}' in 'Imie' text box
            Keyboard.SendKeys(uIImieEdit, this.AddNewPracownikParams.UIImieEditSendKeys, ModifierKeys.None);

            // Type 'Test' in 'Nazwisko' text box
            uINazwiskoEdit.Text = this.AddNewPracownikParams.UINazwiskoEditText;

            // Type '{Tab}' in 'Nazwisko' text box
            Keyboard.SendKeys(uINazwiskoEdit, this.AddNewPracownikParams.UINazwiskoEditSendKeys, ModifierKeys.None);

            // Type '12345678914' in 'Pesel' text box
            uIPeselEdit.Text = this.AddNewPracownikParams.UIPeselEditText;

            // Click 'Create' button
            Mouse.Click(uICreateButton, new Point(32, 29));
        }
        
        /// <summary>
        /// EditPracownik - Use 'EditPracownikParams' to pass parameters into this method.
        /// </summary>
        public void EditPracownik()
        {
            #region Variable Declarations
            HtmlHyperlink uIEditHyperlink1 = this.UIIndexMyASPNETApplicaWindow.UIIndexMyASPNETApplicaDocument.UIEditHyperlink1;
            HtmlEdit uINazwiskoEdit = this.UIIndexMyASPNETApplicaWindow.UIEditMyASPNETApplicatDocument1.UINazwiskoEdit;
            HtmlEdit uIPeselEdit = this.UIIndexMyASPNETApplicaWindow.UIEditMyASPNETApplicatDocument1.UIPeselEdit;
            HtmlInputButton uISaveButton = this.UIIndexMyASPNETApplicaWindow.UIEditMyASPNETApplicatDocument1.UISaveButton;
            #endregion

            // Click 'Edit' link
            Mouse.Click(uIEditHyperlink1, new Point(9, 12));

            // Type 'Testowy' in 'Nazwisko' text box
            uINazwiskoEdit.Text = this.EditPracownikParams.UINazwiskoEditText;

            // Type '12345678918' in 'Pesel' text box
            uIPeselEdit.Text = this.EditPracownikParams.UIPeselEditText;

            // Click 'Save' button
            Mouse.Click(uISaveButton, new Point(45, 16));
        }
        
        /// <summary>
        /// DeletePracownik
        /// </summary>
        public void DeletePracownik()
        {
            #region Variable Declarations
            HtmlHyperlink uIDeleteHyperlink = this.UIIndexMyASPNETApplicaWindow.UIIndexMyASPNETApplicaDocument.UIDeleteHyperlink;
            HtmlInputButton uIDeleteButton = this.UIIndexMyASPNETApplicaWindow.UIDeleteMyASPNETApplicDocument.UIDeleteButton;
            #endregion

            // Click 'Delete' link
            Mouse.Click(uIDeleteHyperlink, new Point(22, 10));

            // Click 'Delete' button
            Mouse.Click(uIDeleteButton, new Point(35, 14));
        }
        
        /// <summary>
        /// Stanowiska
        /// </summary>
        public void Stanowiska()
        {
            #region Variable Declarations
            HtmlHyperlink uIStanowiskaHyperlink = this.UIIndexMyASPNETApplicaWindow.UIIndexMyASPNETApplicaDocument.UIStanowiskaHyperlink;
            #endregion

            // Click 'Stanowiska' link
            Mouse.Click(uIStanowiskaHyperlink, new Point(59, 16));
        }
        
        /// <summary>
        /// AssertionStanowiska - Use 'AssertionStanowiskaExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertionStanowiska()
        {
            #region Variable Declarations
            HtmlHeaderCell uIStanowiskoCell = this.UIIndexMyASPNETApplicaWindow.UIIndexMyASPNETApplicaDocument1.UIItemTable.UIStanowiskoCell;
            #endregion

            // Verify that the 'InnerText' property of 'Stanowisko' cell equals 'Stanowisko '
            Assert.AreEqual(this.AssertionStanowiskaExpectedValues.UIStanowiskoCellInnerText, uIStanowiskoCell.InnerText, "Zły widok");
        }
        
        /// <summary>
        /// test
        /// </summary>
        public void test()
        {
            #region Variable Declarations
            HtmlHyperlink uIPracownicyHyperlink = this.UIIndexMyASPNETApplicaWindow.UIIndexMyASPNETApplicaDocument1.UIPracownicyHyperlink;
            #endregion

            // Click 'Pracownicy' link
            Mouse.Click(uIPracownicyHyperlink, new Point(69, 20));
        }
        
        /// <summary>
        /// fdsfsdf
        /// </summary>
        public void fdsfsdf()
        {

            // Last mouse action was not recorded.
        }
        
        #region Properties
        public virtual OpenBrowseParams OpenBrowseParams
        {
            get
            {
                if ((this.mOpenBrowseParams == null))
                {
                    this.mOpenBrowseParams = new OpenBrowseParams();
                }
                return this.mOpenBrowseParams;
            }
        }
        
        public virtual OpenAppParams OpenAppParams
        {
            get
            {
                if ((this.mOpenAppParams == null))
                {
                    this.mOpenAppParams = new OpenAppParams();
                }
                return this.mOpenAppParams;
            }
        }
        
        public virtual AddNewPracownikParams AddNewPracownikParams
        {
            get
            {
                if ((this.mAddNewPracownikParams == null))
                {
                    this.mAddNewPracownikParams = new AddNewPracownikParams();
                }
                return this.mAddNewPracownikParams;
            }
        }
        
        public virtual EditPracownikParams EditPracownikParams
        {
            get
            {
                if ((this.mEditPracownikParams == null))
                {
                    this.mEditPracownikParams = new EditPracownikParams();
                }
                return this.mEditPracownikParams;
            }
        }
        
        public virtual AssertionStanowiskaExpectedValues AssertionStanowiskaExpectedValues
        {
            get
            {
                if ((this.mAssertionStanowiskaExpectedValues == null))
                {
                    this.mAssertionStanowiskaExpectedValues = new AssertionStanowiskaExpectedValues();
                }
                return this.mAssertionStanowiskaExpectedValues;
            }
        }
        
        public UIMSNPolskaOutlookSkypWindow UIMSNPolskaOutlookSkypWindow
        {
            get
            {
                if ((this.mUIMSNPolskaOutlookSkypWindow == null))
                {
                    this.mUIMSNPolskaOutlookSkypWindow = new UIMSNPolskaOutlookSkypWindow();
                }
                return this.mUIMSNPolskaOutlookSkypWindow;
            }
        }
        
        public UIIndexMyASPNETApplicaWindow UIIndexMyASPNETApplicaWindow
        {
            get
            {
                if ((this.mUIIndexMyASPNETApplicaWindow == null))
                {
                    this.mUIIndexMyASPNETApplicaWindow = new UIIndexMyASPNETApplicaWindow();
                }
                return this.mUIIndexMyASPNETApplicaWindow;
            }
        }
        #endregion
        
        #region Fields
        private OpenBrowseParams mOpenBrowseParams;
        
        private OpenAppParams mOpenAppParams;
        
        private AddNewPracownikParams mAddNewPracownikParams;
        
        private EditPracownikParams mEditPracownikParams;
        
        private AssertionStanowiskaExpectedValues mAssertionStanowiskaExpectedValues;
        
        private UIMSNPolskaOutlookSkypWindow mUIMSNPolskaOutlookSkypWindow;
        
        private UIIndexMyASPNETApplicaWindow mUIIndexMyASPNETApplicaWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'OpenBrowse'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class OpenBrowseParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=255141' using new browser instance
        /// </summary>
        public string Url = "http://go.microsoft.com/fwlink/p/?LinkId=255141";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'OpenApp'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class OpenAppParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:21867/'
        /// </summary>
        public string UIMSNPolskaOutlookSkypWindowUrl = "http://localhost:21867/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AddNewPracownik'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AddNewPracownikParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Szef' in 'StanowiskoId' combo box
        /// </summary>
        public string UIStanowiskoIdComboBoxSelectedItem = "Szef";
        
        /// <summary>
        /// Type 'Test' in 'Imie' text box
        /// </summary>
        public string UIImieEditText = "Test";
        
        /// <summary>
        /// Type '{Tab}' in 'Imie' text box
        /// </summary>
        public string UIImieEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Test' in 'Nazwisko' text box
        /// </summary>
        public string UINazwiskoEditText = "Test";
        
        /// <summary>
        /// Type '{Tab}' in 'Nazwisko' text box
        /// </summary>
        public string UINazwiskoEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '12345678914' in 'Pesel' text box
        /// </summary>
        public string UIPeselEditText = "12345678914";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EditPracownik'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class EditPracownikParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Testowy' in 'Nazwisko' text box
        /// </summary>
        public string UINazwiskoEditText = "Testowy";
        
        /// <summary>
        /// Type '12345678918' in 'Pesel' text box
        /// </summary>
        public string UIPeselEditText = "12345678918";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertionStanowiska'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AssertionStanowiskaExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Stanowisko' cell equals 'Stanowisko '
        /// </summary>
        public string UIStanowiskoCellInnerText = "Stanowisko ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMSNPolskaOutlookSkypWindow : BrowserWindow
    {
        
        public UIMSNPolskaOutlookSkypWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MSN Polska - Outlook, Skype, Hotmail, Messenger, Microsoft Office Online i OneDri" +
                "ve";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("MSN Polska - Outlook, Skype, Hotmail, Messenger, Microsoft Office Online i OneDri" +
                    "ve");
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageMyASPNETApplDocument UIHomePageMyASPNETApplDocument
        {
            get
            {
                if ((this.mUIHomePageMyASPNETApplDocument == null))
                {
                    this.mUIHomePageMyASPNETApplDocument = new UIHomePageMyASPNETApplDocument(this);
                }
                return this.mUIHomePageMyASPNETApplDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageMyASPNETApplDocument mUIHomePageMyASPNETApplDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePageMyASPNETApplDocument : HtmlDocument
    {
        
        public UIHomePageMyASPNETApplDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:21867/";
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIPracownicyHyperlink
        {
            get
            {
                if ((this.mUIPracownicyHyperlink == null))
                {
                    this.mUIPracownicyHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIPracownicyHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIPracownicyHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIPracownicyHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIPracownicyHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Pracownicy";
                    this.mUIPracownicyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Pracownicy";
                    this.mUIPracownicyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIPracownicyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:21867/Pracownicy";
                    this.mUIPracownicyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIPracownicyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Pracownicy\"";
                    this.mUIPracownicyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIPracownicyHyperlink.WindowTitles.Add("Home Page - My ASP.NET Application");
                    #endregion
                }
                return this.mUIPracownicyHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIPracownicyHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexMyASPNETApplicaWindow : BrowserWindow
    {
        
        public UIIndexMyASPNETApplicaWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Index - My ASP.NET Application";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Index - My ASP.NET Application");
            this.WindowTitles.Add("Create - My ASP.NET Application");
            this.WindowTitles.Add("Edit - My ASP.NET Application");
            this.WindowTitles.Add("Delete - My ASP.NET Application");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIIndexMyASPNETApplicaDocument UIIndexMyASPNETApplicaDocument
        {
            get
            {
                if ((this.mUIIndexMyASPNETApplicaDocument == null))
                {
                    this.mUIIndexMyASPNETApplicaDocument = new UIIndexMyASPNETApplicaDocument(this);
                }
                return this.mUIIndexMyASPNETApplicaDocument;
            }
        }
        
        public UICreateMyASPNETApplicDocument UICreateMyASPNETApplicDocument
        {
            get
            {
                if ((this.mUICreateMyASPNETApplicDocument == null))
                {
                    this.mUICreateMyASPNETApplicDocument = new UICreateMyASPNETApplicDocument(this);
                }
                return this.mUICreateMyASPNETApplicDocument;
            }
        }
        
        public UIEditMyASPNETApplicatDocument UIEditMyASPNETApplicatDocument
        {
            get
            {
                if ((this.mUIEditMyASPNETApplicatDocument == null))
                {
                    this.mUIEditMyASPNETApplicatDocument = new UIEditMyASPNETApplicatDocument(this);
                }
                return this.mUIEditMyASPNETApplicatDocument;
            }
        }
        
        public UIDeleteMyASPNETApplicDocument UIDeleteMyASPNETApplicDocument
        {
            get
            {
                if ((this.mUIDeleteMyASPNETApplicDocument == null))
                {
                    this.mUIDeleteMyASPNETApplicDocument = new UIDeleteMyASPNETApplicDocument(this);
                }
                return this.mUIDeleteMyASPNETApplicDocument;
            }
        }
        
        public UIEditMyASPNETApplicatDocument1 UIEditMyASPNETApplicatDocument1
        {
            get
            {
                if ((this.mUIEditMyASPNETApplicatDocument1 == null))
                {
                    this.mUIEditMyASPNETApplicatDocument1 = new UIEditMyASPNETApplicatDocument1(this);
                }
                return this.mUIEditMyASPNETApplicatDocument1;
            }
        }
        
        public UIIndexMyASPNETApplicaDocument1 UIIndexMyASPNETApplicaDocument1
        {
            get
            {
                if ((this.mUIIndexMyASPNETApplicaDocument1 == null))
                {
                    this.mUIIndexMyASPNETApplicaDocument1 = new UIIndexMyASPNETApplicaDocument1(this);
                }
                return this.mUIIndexMyASPNETApplicaDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIIndexMyASPNETApplicaDocument mUIIndexMyASPNETApplicaDocument;
        
        private UICreateMyASPNETApplicDocument mUICreateMyASPNETApplicDocument;
        
        private UIEditMyASPNETApplicatDocument mUIEditMyASPNETApplicatDocument;
        
        private UIDeleteMyASPNETApplicDocument mUIDeleteMyASPNETApplicDocument;
        
        private UIEditMyASPNETApplicatDocument1 mUIEditMyASPNETApplicatDocument1;
        
        private UIIndexMyASPNETApplicaDocument1 mUIIndexMyASPNETApplicaDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexMyASPNETApplicaDocument : HtmlDocument
    {
        
        public UIIndexMyASPNETApplicaDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Pracownicy";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:21867/Pracownicy";
            this.WindowTitles.Add("Index - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UICreateNewHyperlink
        {
            get
            {
                if ((this.mUICreateNewHyperlink == null))
                {
                    this.mUICreateNewHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Create New";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Pracownicy/Create";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:21867/Pracownicy/Create";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Pracownicy/Create\"";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "5";
                    this.mUICreateNewHyperlink.WindowTitles.Add("Index - My ASP.NET Application");
                    #endregion
                }
                return this.mUICreateNewHyperlink;
            }
        }
        
        public HtmlHyperlink UIEditHyperlink
        {
            get
            {
                if ((this.mUIEditHyperlink == null))
                {
                    this.mUIEditHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEditHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEditHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEditHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEditHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Edit";
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Pracownicy/Edit/1";
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:21867/Pracownicy/Edit/1";
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Pracownicy/Edit/1\"";
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "6";
                    this.mUIEditHyperlink.WindowTitles.Add("Index - My ASP.NET Application");
                    #endregion
                }
                return this.mUIEditHyperlink;
            }
        }
        
        public HtmlHyperlink UIDeleteHyperlink
        {
            get
            {
                if ((this.mUIDeleteHyperlink == null))
                {
                    this.mUIDeleteHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Delete";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Pracownicy/Delete/5";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:21867/Pracownicy/Delete/5";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Pracownicy/Delete/5\"";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "20";
                    this.mUIDeleteHyperlink.WindowTitles.Add("Index - My ASP.NET Application");
                    #endregion
                }
                return this.mUIDeleteHyperlink;
            }
        }
        
        public HtmlHyperlink UIEditHyperlink1
        {
            get
            {
                if ((this.mUIEditHyperlink1 == null))
                {
                    this.mUIEditHyperlink1 = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEditHyperlink1.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEditHyperlink1.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEditHyperlink1.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEditHyperlink1.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Edit";
                    this.mUIEditHyperlink1.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Pracownicy/Edit/9";
                    this.mUIEditHyperlink1.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIEditHyperlink1.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:21867/Pracownicy/Edit/9";
                    this.mUIEditHyperlink1.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIEditHyperlink1.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Pracownicy/Edit/9\"";
                    this.mUIEditHyperlink1.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "18";
                    this.mUIEditHyperlink1.WindowTitles.Add("Index - My ASP.NET Application");
                    #endregion
                }
                return this.mUIEditHyperlink1;
            }
        }
        
        public HtmlHyperlink UIStanowiskaHyperlink
        {
            get
            {
                if ((this.mUIStanowiskaHyperlink == null))
                {
                    this.mUIStanowiskaHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIStanowiskaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIStanowiskaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIStanowiskaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIStanowiskaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Stanowiska";
                    this.mUIStanowiskaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Stanowiska";
                    this.mUIStanowiskaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIStanowiskaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:21867/Stanowiska";
                    this.mUIStanowiskaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIStanowiskaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Stanowiska\"";
                    this.mUIStanowiskaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIStanowiskaHyperlink.WindowTitles.Add("Index - My ASP.NET Application");
                    #endregion
                }
                return this.mUIStanowiskaHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUICreateNewHyperlink;
        
        private HtmlHyperlink mUIEditHyperlink;
        
        private HtmlHyperlink mUIDeleteHyperlink;
        
        private HtmlHyperlink mUIEditHyperlink1;
        
        private HtmlHyperlink mUIStanowiskaHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICreateMyASPNETApplicDocument : HtmlDocument
    {
        
        public UICreateMyASPNETApplicDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Create - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Pracownicy/Create";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:21867/Pracownicy/Create";
            this.WindowTitles.Add("Create - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UIStanowiskoIdComboBox
        {
            get
            {
                if ((this.mUIStanowiskoIdComboBox == null))
                {
                    this.mUIStanowiskoIdComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIStanowiskoIdComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "StanowiskoId";
                    this.mUIStanowiskoIdComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "StanowiskoId";
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "StanowiskoId";
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "4";
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "form-control";
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"StanowiskoId\" class=\"form-control\"";
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIStanowiskoIdComboBox.WindowTitles.Add("Create - My ASP.NET Application");
                    #endregion
                }
                return this.mUIStanowiskoIdComboBox;
            }
        }
        
        public HtmlEdit UIImieEdit
        {
            get
            {
                if ((this.mUIImieEdit == null))
                {
                    this.mUIImieEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIImieEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Imie";
                    this.mUIImieEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Imie";
                    this.mUIImieEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Imie";
                    this.mUIImieEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIImieEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIImieEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUIImieEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Imie\" class=\"form-control text-box";
                    this.mUIImieEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIImieEdit.WindowTitles.Add("Create - My ASP.NET Application");
                    #endregion
                }
                return this.mUIImieEdit;
            }
        }
        
        public HtmlEdit UINazwiskoEdit
        {
            get
            {
                if ((this.mUINazwiskoEdit == null))
                {
                    this.mUINazwiskoEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINazwiskoEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Nazwisko";
                    this.mUINazwiskoEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Nazwisko";
                    this.mUINazwiskoEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Nazwisko";
                    this.mUINazwiskoEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINazwiskoEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINazwiskoEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUINazwiskoEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Nazwisko\" class=\"form-control text";
                    this.mUINazwiskoEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUINazwiskoEdit.WindowTitles.Add("Create - My ASP.NET Application");
                    #endregion
                }
                return this.mUINazwiskoEdit;
            }
        }
        
        public HtmlEdit UIPeselEdit
        {
            get
            {
                if ((this.mUIPeselEdit == null))
                {
                    this.mUIPeselEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPeselEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Pesel";
                    this.mUIPeselEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Pesel";
                    this.mUIPeselEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Pesel";
                    this.mUIPeselEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPeselEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPeselEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUIPeselEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Pesel\" class=\"form-control text-bo";
                    this.mUIPeselEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIPeselEdit.WindowTitles.Add("Create - My ASP.NET Application");
                    #endregion
                }
                return this.mUIPeselEdit;
            }
        }
        
        public HtmlInputButton UICreateButton
        {
            get
            {
                if ((this.mUICreateButton == null))
                {
                    this.mUICreateButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Name] = "Create";
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Create";
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"Create\" class=\"btn btn-default\" ty";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "5";
                    this.mUICreateButton.WindowTitles.Add("Create - My ASP.NET Application");
                    #endregion
                }
                return this.mUICreateButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUIStanowiskoIdComboBox;
        
        private HtmlEdit mUIImieEdit;
        
        private HtmlEdit mUINazwiskoEdit;
        
        private HtmlEdit mUIPeselEdit;
        
        private HtmlInputButton mUICreateButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIEditMyASPNETApplicatDocument : HtmlDocument
    {
        
        public UIEditMyASPNETApplicatDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Edit - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Pracownicy/Edit/1";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:21867/Pracownicy/Edit/1";
            this.WindowTitles.Add("Edit - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIImieEdit
        {
            get
            {
                if ((this.mUIImieEdit == null))
                {
                    this.mUIImieEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIImieEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Imie";
                    this.mUIImieEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Imie";
                    this.mUIImieEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Imie";
                    this.mUIImieEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIImieEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIImieEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUIImieEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Imie\" class=\"form-control text-box";
                    this.mUIImieEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIImieEdit.WindowTitles.Add("Edit - My ASP.NET Application");
                    #endregion
                }
                return this.mUIImieEdit;
            }
        }
        
        public HtmlComboBox UIStanowiskoIdComboBox
        {
            get
            {
                if ((this.mUIStanowiskoIdComboBox == null))
                {
                    this.mUIStanowiskoIdComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIStanowiskoIdComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "StanowiskoId";
                    this.mUIStanowiskoIdComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "StanowiskoId";
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "StanowiskoId";
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "4";
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "form-control";
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"StanowiskoId\" class=\"form-control\"";
                    this.mUIStanowiskoIdComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIStanowiskoIdComboBox.WindowTitles.Add("Edit - My ASP.NET Application");
                    #endregion
                }
                return this.mUIStanowiskoIdComboBox;
            }
        }
        
        public HtmlInputButton UISaveButton
        {
            get
            {
                if ((this.mUISaveButton == null))
                {
                    this.mUISaveButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Save";
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\" va";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "6";
                    this.mUISaveButton.WindowTitles.Add("Edit - My ASP.NET Application");
                    #endregion
                }
                return this.mUISaveButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIImieEdit;
        
        private HtmlComboBox mUIStanowiskoIdComboBox;
        
        private HtmlInputButton mUISaveButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDeleteMyASPNETApplicDocument : HtmlDocument
    {
        
        public UIDeleteMyASPNETApplicDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Delete - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Pracownicy/Delete/5";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:21867/Pracownicy/Delete/5";
            this.WindowTitles.Add("Delete - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UIDeleteButton
        {
            get
            {
                if ((this.mUIDeleteButton == null))
                {
                    this.mUIDeleteButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIDeleteButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIDeleteButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIDeleteButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Delete";
                    this.mUIDeleteButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIDeleteButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIDeleteButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIDeleteButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\" va";
                    this.mUIDeleteButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUIDeleteButton.WindowTitles.Add("Delete - My ASP.NET Application");
                    #endregion
                }
                return this.mUIDeleteButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUIDeleteButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIEditMyASPNETApplicatDocument1 : HtmlDocument
    {
        
        public UIEditMyASPNETApplicatDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Edit - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Pracownicy/Edit/9";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:21867/Pracownicy/Edit/9";
            this.WindowTitles.Add("Edit - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UINazwiskoEdit
        {
            get
            {
                if ((this.mUINazwiskoEdit == null))
                {
                    this.mUINazwiskoEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINazwiskoEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Nazwisko";
                    this.mUINazwiskoEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Nazwisko";
                    this.mUINazwiskoEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Nazwisko";
                    this.mUINazwiskoEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINazwiskoEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINazwiskoEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUINazwiskoEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Nazwisko\" class=\"form-control text";
                    this.mUINazwiskoEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUINazwiskoEdit.WindowTitles.Add("Edit - My ASP.NET Application");
                    #endregion
                }
                return this.mUINazwiskoEdit;
            }
        }
        
        public HtmlEdit UIPeselEdit
        {
            get
            {
                if ((this.mUIPeselEdit == null))
                {
                    this.mUIPeselEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPeselEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Pesel";
                    this.mUIPeselEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Pesel";
                    this.mUIPeselEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Pesel";
                    this.mUIPeselEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPeselEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPeselEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUIPeselEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Pesel\" class=\"form-control text-bo";
                    this.mUIPeselEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIPeselEdit.WindowTitles.Add("Edit - My ASP.NET Application");
                    #endregion
                }
                return this.mUIPeselEdit;
            }
        }
        
        public HtmlInputButton UISaveButton
        {
            get
            {
                if ((this.mUISaveButton == null))
                {
                    this.mUISaveButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Save";
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\" va";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "6";
                    this.mUISaveButton.WindowTitles.Add("Edit - My ASP.NET Application");
                    #endregion
                }
                return this.mUISaveButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUINazwiskoEdit;
        
        private HtmlEdit mUIPeselEdit;
        
        private HtmlInputButton mUISaveButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexMyASPNETApplicaDocument1 : HtmlDocument
    {
        
        public UIIndexMyASPNETApplicaDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Stanowiska";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:21867/Stanowiska";
            this.WindowTitles.Add("Index - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        
        public HtmlHyperlink UIPracownicyHyperlink
        {
            get
            {
                if ((this.mUIPracownicyHyperlink == null))
                {
                    this.mUIPracownicyHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIPracownicyHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIPracownicyHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIPracownicyHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIPracownicyHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Pracownicy";
                    this.mUIPracownicyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Pracownicy";
                    this.mUIPracownicyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIPracownicyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:21867/Pracownicy";
                    this.mUIPracownicyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIPracownicyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Pracownicy\"";
                    this.mUIPracownicyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIPracownicyHyperlink.WindowTitles.Add("Index - My ASP.NET Application");
                    #endregion
                }
                return this.mUIPracownicyHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable mUIItemTable;
        
        private HtmlHyperlink mUIPracownicyHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Stanowisko \r\n\r\nPensja \r\n\r\n\r\nKucharz 400,";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"table\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "5";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "3";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "table";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Index - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlHeaderCell UIStanowiskoCell
        {
            get
            {
                if ((this.mUIStanowiskoCell == null))
                {
                    this.mUIStanowiskoCell = new HtmlHeaderCell(this);
                    #region Search Criteria
                    this.mUIStanowiskoCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIStanowiskoCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIStanowiskoCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIStanowiskoCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Stanowisko ";
                    this.mUIStanowiskoCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIStanowiskoCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIStanowiskoCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIStanowiskoCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIStanowiskoCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1";
                    this.mUIStanowiskoCell.WindowTitles.Add("Index - My ASP.NET Application");
                    #endregion
                }
                return this.mUIStanowiskoCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHeaderCell mUIStanowiskoCell;
        #endregion
    }
}
